### ISSUE TITLE
Plotly 4.14.3 + Kaleido 0.2.0 - Import error on Linux

### ISSUE THREAD

**Issue by Djeramon** [plotly/plotly.py#3101]
**Environment:**

Operating system: RedHat Linux 7
Python version: 3.6.8

**Error**:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myuser/.local/lib/python3.6/site-packages/plotly/__init__.py", line 34, in <module>
    from plotly import (
  File "/home/myuser/.local/lib/python3.6/site-packages/plotly/io/__init__.py", line 5, in <module>
    from ._kaleido import to_image, write_image, full_figure_for_development
  File "/home/myuser/.local/lib/python3.6/site-packages/plotly/io/_kaleido.py", line 9, in <module>
    from kaleido.scopes.plotly import PlotlyScope
  File "/home/myuser/.local/lib/python3.6/site-packages/kaleido/scopes/plotly.py", line 3, in <module>
    import plotly.io as pio
AttributeError: module 'plotly' has no attribute 'io'
```

**How to reproduce:**

Install packages:
```
pip3 install kaleido==0.2.0
pip3 install plotly==4.14.3
```

Try to import plotly:
```
import plotly
```

**Other interesting information:**

The same combination of versions works fine on a Windows OS.

**Comment by boehmseb** [comment]
I run into the same issue, but only with Python 3.6. It works with 3.7. Also this only happens with kaleido 0.2.0.

**Comment by jonmmease** [comment]
Thanks for the report. 

Looks like an import cycle that for some reason Python 3.6 can't resolve. Fix to kaleido on the way, but it may not be until tomorrow before the everthing churns through the release process. If you are hitting this problem, please continue to use version 0.1.0 until 0.2.1 is out.

**Comment by jonmmease** [comment]
@boehmseb @Djeramon Please try the 0.2.1 release from the Kaleido GitHub release page (I'm going to wait to upload to PyPI and anaconda.org until something gives a 👍 that this fixed this issue for them)



For linux x86_64:
```
pip install https://github.com/plotly/Kaleido/releases/download/v0.2.1/kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl
```

for other operating systems, look for the appropriate wheel file under https://github.com/plotly/Kaleido/releases/tag/v0.2.1, and pip install using the full url.

Thank!

**Comment by Djeramon** [comment]
I can confirm that kaleido 0.2.1 fixed the issue. Thanks for this quick fix.

**Comment by boehmseb** [comment]
Also works for me, thanks.

**Comment by jonmmease** [comment]
Great! Thanks for trying it out. 0.2.1 Packages are now published to PyPI and conda-forge.
